
"use client";

import { useState, useEffect } from "react";
import { PageHeader } from "@/components/shared/PageHeader";
import { BookingForm, type BookingFormValues } from "@/components/forms/BookingForm";
import type { Salon, Hairdresser, User, BookingDoc, LocationDoc, HairdresserDoc } from "@/lib/types";
import { PlusCircle, Loader2 } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { useRouter } from 'next/navigation';
import { useAuth } from "@/contexts/AuthContext";
import { db, collection, addDoc, getDocs, serverTimestamp, Timestamp } from "@/lib/firebase";

// This is the function that SHOULD be called to save to Firestore.
async function createBookingInFirestore(data: BookingFormValues, currentUser: User | null): Promise<string> {
  console.log("==> [NEW_PAGE_Firestore] Attempting to create booking. Form data:", JSON.stringify(data, null, 2));
  console.log("==> [NEW_PAGE_Firestore] Current user:", currentUser ? JSON.stringify(currentUser, null, 2) : "NULL");

  if (!currentUser) {
    console.error("==> [NEW_PAGE_Firestore] No current user available. Aborting!");
    toast({
      title: "Authentication Error",
      description: "You must be logged in to create a booking. Please refresh and log in again.",
      variant: "destructive"
    });
    throw new Error("User not authenticated. Cannot create booking.");
  }

  // data.appointmentDateTime from BookingForm is already the combined Date object
  const appointmentDateForFirestore = Timestamp.fromDate(data.appointmentDateTime);
  console.log("==> [NEW_PAGE_Firestore] Converted appointmentDateTime to Firestore Timestamp:", appointmentDateForFirestore);

  const newBookingDoc: Omit<BookingDoc, 'id'> = { // 'id' is auto-generated by Firestore
    clientName: data.clientName,
    clientEmail: data.clientEmail || "",
    clientPhone: data.clientPhone,
    salonId: data.salonId,
    hairdresserId: data.hairdresserId,
    service: data.service,
    appointmentDateTime: appointmentDateForFirestore,
    durationMinutes: data.durationMinutes,
    status: 'Confirmed', // Default status for a new booking
    notes: data.notes || "",
    createdAt: serverTimestamp() as Timestamp,
    updatedAt: serverTimestamp() as Timestamp,
  };
  console.log("==> [NEW_PAGE_Firestore] Prepared Firestore document data:", JSON.stringify(newBookingDoc, null, 2));

  try {
    console.log("==> [NEW_PAGE_Firestore] Calling addDoc to 'bookings' collection with db instance:", db ? "DB INSTANCE OK" : "DB INSTANCE NULL/UNDEFINED");
    if (!db) {
        console.error("==> [NEW_PAGE_Firestore] Firestore DB instance is not available. Aborting addDoc call.");
        throw new Error("Firestore DB instance not available.");
    }
    const docRef = await addDoc(collection(db, "bookings"), newBookingDoc);
    console.log("==> [NEW_PAGE_Firestore] Successfully created booking with Firestore ID:", docRef.id);
    toast({ title: "Booking Created", description: `Appointment for ${data.clientName} has been successfully scheduled.` });
    return docRef.id;
  } catch (error: any) {
    console.error("==> [NEW_PAGE_Firestore] Error writing document to Firestore:", error);
    try {
      console.error("==> [NEW_PAGE_Firestore] Full error object stringified:", JSON.stringify(error, Object.getOwnPropertyNames(error)));
    } catch (stringifyError) {
      console.error("==> [NEW_PAGE_Firestore] Could not stringify the full error object:", stringifyError);
    }
    toast({
      title: "Booking Creation Failed",
      description: `Could not save booking to database. Error: ${error.message || 'Unknown error'}. Please check browser console for more details.`,
      variant: "destructive"
    });
    throw error;
  }
}


export default function NewBookingPage() {
  const { user } = useAuth();
  const [salons, setSalons] = useState<Salon[]>([]);
  const [hairdressers, setHairdressers] = useState<Hairdresser[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const router = useRouter();
  const [initialFormValues, setInitialFormValues] = useState<Partial<BookingFormValues>>({});


  useEffect(() => {
    console.log("==> [NEW_PAGE_Effect] useEffect triggered. Auth User object:", user ? JSON.stringify(user, null, 2).substring(0,300) + "..." : "NULL");
    if (!user) {
      console.log("==> [NEW_PAGE_Effect] No user authenticated, data fetching will be skipped.");
      setIsLoading(false);
      return;
    }

    const fetchData = async () => {
      console.log("==> [NEW_PAGE_Effect_FetchData] fetchData started.");
      console.log("==> [NEW_PAGE_Effect_FetchData] Checking Firestore db instance:", db ? "DB INSTANCE OK" : "DB INSTANCE NULL/UNDEFINED");
      if (!db) {
        console.error("==> [NEW_PAGE_Effect_FetchData] Firestore DB instance is not available. Cannot fetch data.");
        toast({ title: "Configuration Error", description: "Firestore database is not configured. Please contact support.", variant: "destructive" });
        setIsLoading(false);
        return;
      }
      setIsLoading(true);
      try {
        console.log("==> [NEW_PAGE_Effect_FetchData] Fetching salons from 'locations' collection...");
        const locationsCol = collection(db, "locations");
        const locationSnapshot = await getDocs(locationsCol);
        const salonsList = locationSnapshot.docs.map(sDoc => ({
          id: sDoc.id,
          ...(sDoc.data() as LocationDoc)
        } as Salon));
        console.log(`==> [NEW_PAGE_Effect_FetchData] Fetched ${salonsList.length} salons:`, JSON.stringify(salonsList, null, 2).substring(0, 200) + "...");
        setSalons(salonsList);

        console.log("==> [NEW_PAGE_Effect_FetchData] Fetching hairdressers from 'hairdressers' collection...");
        const hairdressersCol = collection(db, "hairdressers");
        const hairdresserSnapshot = await getDocs(hairdressersCol);
        console.log(`==> [NEW_PAGE_Effect_FetchData] Hairdresser snapshot has ${hairdresserSnapshot.docs.length} documents.`);

        if (hairdresserSnapshot.empty) {
            console.warn("==> [NEW_PAGE_Effect_FetchData] No documents found in the 'hairdressers' collection.");
        }

        const hairdressersList = hairdresserSnapshot.docs.map(hDoc => {
          const data = hDoc.data() as HairdresserDoc;
          console.log(`==> [NEW_PAGE_Effect_FetchData] Raw data for hairdresser doc ${hDoc.id}:`, JSON.stringify(data, null, 2).substring(0, 200) + "...");
          const mappedHairdresser: Hairdresser = {
            id: hDoc.id,
            userId: data.user_id,
            name: data.name,
            email: data.email,
            assigned_locations: data.assigned_locations || [], // CRITICAL for form filtering
            specialties: data.specialties || [],
            availability: data.availability || "",
            working_days: data.working_days || [],
            profilePictureUrl: data.profilePictureUrl || "",
            must_reset_password: data.must_reset_password || false,
            createdAt: data.createdAt,
            updatedAt: data.updatedAt,
          };
          console.log(`==> [NEW_PAGE_Effect_FetchData] Mapped hairdresser ${hDoc.id}: Name: ${mappedHairdresser.name}, Assigned Locations: ${JSON.stringify(mappedHairdresser.assigned_locations)}`);
          return mappedHairdresser;
        });
        console.log(`==> [NEW_PAGE_Effect_FetchData] Mapped ${hairdressersList.length} hairdressers. Full list (first 200 chars):`, JSON.stringify(hairdressersList, null, 2).substring(0, 200) + "...");
        setHairdressers(hairdressersList);

        const prefillValues: Partial<BookingFormValues> = {};
        if (user?.role === 'hairdresser' && user.hairdresserProfileId) {
            console.log("==> [NEW_PAGE_Effect_FetchData] User is hairdresser, attempting to prefill form.");
            prefillValues.hairdresserId = user.hairdresserProfileId;
            const hairdresserDetails = hairdressersList.find(h => h.id === user.hairdresserProfileId);
            if (hairdresserDetails && hairdresserDetails.assigned_locations.length > 0) {
                prefillValues.salonId = hairdresserDetails.assigned_locations[0];
                console.log("==> [NEW_PAGE_Effect_FetchData] Prefilling salonId:", hairdresserDetails.assigned_locations[0]);
            } else if (hairdresserDetails) {
                 console.warn("==> [NEW_PAGE_Effect_FetchData] Hairdresser has no assigned locations, salonId will not be prefilled.");
            } else {
                 console.warn("==> [NEW_PAGE_Effect_FetchData] Could not find hairdresser details for prefill with ID:", user.hairdresserProfileId);
            }
            console.log("==> [NEW_PAGE_Effect_FetchData] Prefill values for hairdresser:", JSON.stringify(prefillValues, null, 2));
        }
        setInitialFormValues(prefillValues);

      } catch (error: any) {
        console.error("==> [NEW_PAGE_Effect_FetchData] Error fetching data for new booking:", error);
        toast({ title: "Error Loading Data", description: `Could not load required data: ${error.message}. Check console for details.`, variant: "destructive" });
      } finally {
        console.log("==> [NEW_PAGE_Effect_FetchData] fetchData finished.");
        setIsLoading(false);
      }
    };

    fetchData();
  }, [user]);

  const handleCreateBooking = async (data: BookingFormValues) => {
    console.log("==> [NEW_PAGE_HandleSubmit] Starting booking creation process. Form data:", JSON.stringify(data, null, 2));
    console.log("==> [NEW_PAGE_HandleSubmit] Current auth user from useAuth():", user ? JSON.stringify(user, null, 2).substring(0,300) + "..." : "NULL");

    if (!user) {
        console.error("==> [NEW_PAGE_HandleSubmit] Critical: No user object available from useAuth() hook. Cannot proceed with booking creation.");
        toast({
            title: "Authentication Error",
            description: "Cannot create booking: User is not authenticated. Please log in again.",
            variant: "destructive",
        });
        setIsSubmitting(false);
        return;
    }

    setIsSubmitting(true);
    try {
      await createBookingInFirestore(data, user);
      console.log("==> [NEW_PAGE_HandleSubmit] Booking creation reported as successful, navigating...");
      router.push(user?.role === 'hairdresser' ? '/bookings?view=mine' : '/bookings');
    } catch (error) {
      console.error("==> [NEW_PAGE_HandleSubmit] Failed to create booking (error caught from createBookingInFirestore):", error);
      // Toast for error is handled within createBookingInFirestore
    } finally {
      console.log("==> [NEW_PAGE_HandleSubmit] Booking creation process finished.");
      setIsSubmitting(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-full">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
        <span className="ml-2">Loading booking form...</span>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <PageHeader
        title="New Booking"
        description="Schedule a new appointment for a client."
        icon={PlusCircle}
      />
      <BookingForm
        salons={salons}
        allHairdressers={hairdressers}
        onSubmit={handleCreateBooking}
        initialDataPreselected={initialFormValues}
        isSubmitting={isSubmitting} // Pass the isSubmitting state here
      />
    </div>
  );
}

    